/* ============================================================================
   sundisk.js  ::  the capital, generated.

   Concentric, palace at the exact centre, reflecting the sun's radiance
   spreading outward. Every building comes out of a district ruleset. Nothing
   here is hand placed except the six landmarks canon names individually, and
   even those are built from rules rather than from a list of coordinates.

     Inner Ring, the Golden Circle    0 to 1,200 m     ~40,000 people
     Middle Ring, markets and trade   1,200 to 3,000   ~350,000
     Outer Ring, common districts     3,000 to 5,500   ~800,000
     The Great Wall                   5,500 m
     The Commons, extramural          5,500 to 9,000   ~300,000

   Eighteen kilometres across. A person walking at 4 km/h crosses it in four
   and a half hours, and that is arithmetic, not a feeling to be faked.

   THE COMMONS ARE THE POINT. Inside the wall is planned, gridded and walled.
   Outside it is a spreading stain: no grid, alleys 1.5 to 3 m, organic
   branching, clustered on wells and shared ovens. The transition has to be
   legible from the air in one glance, so the two are generated by completely
   different algorithms rather than by the same one with a density knob.
   ========================================================================= */

import * as THREE from 'three';
import { CITY_GROUND_Y } from '../terrain/height.js';
import { InstanceSet, geometryKit } from './kit.js';
import { goldRatio } from './materials.js';
import { makeRng, seedFrom } from '../world.js';

export const CITY = {
  /* Part 4.1. OPEN O-1: the 18 km metro is derived from 1.5 million people at
     roughly 40,000 per square mile, not stated in canon. */
  inner: 1200,
  middle: 3000,
  outer: 5500,
  wall: 5500,
  commons: 9000,
  metroDiameter: 18000,

  /* OPEN O-6: canon says the wall is "3 m+". At a capital of 1.5 million that
     is low, so this model builds it at 9 m with a 3 m parapet. */
  wallHeight: 9,
  wallParapet: 3,
  wallThickness: 4.5,
  towerSpacing: 180,

  /* Part 4.2 areas, in square metres. */
  palaceArea: 202000,        // 50 acres
  marketArea: 121000,        // 30 acres
  templeCapacity: 10000,

  /* The prevailing Harmattan comes out of the northeast, so downwind is
     southwest. The slave quarters are west, the kilns and tanneries beyond
     them, because that is where cities put what they do not want to smell. */
  downwind: { x: -Math.SQRT1_2, z: Math.SQRT1_2 },

  gates: [
    { name: 'Gate of the Rising Sun', bearing: 90, service: false },
    { name: 'Gate of the Salt Road', bearing: 270, service: false },
    { name: 'Gate of the Ashteeth', bearing: 0, service: false },
    { name: 'Gate of the Sea', bearing: 180, service: false },
    { name: 'Kiln Gate', bearing: 225, service: true },
    { name: 'Cattle Gate', bearing: 45, service: true },
  ],
};

const G = CITY_GROUND_Y;

/* District rules. wealth drives the gold ratio, spacing drives density, and
   height is what a district can afford to build. */
const DISTRICTS = [
  { id: 'golden', r0: 0, r1: CITY.inner, wealth: 1.00, spacing: 42, h: [10, 19], cover: 0.80 },
  { id: 'market', r0: CITY.inner, r1: 2100, wealth: 0.62, spacing: 26, h: [8, 15], cover: 0.92 },
  { id: 'caravan', r0: 2100, r1: CITY.middle, wealth: 0.48, spacing: 27, h: [7, 13], cover: 0.90 },
  { id: 'common', r0: CITY.middle, r1: 4400, wealth: 0.26, spacing: 19, h: [5, 10], cover: 0.93 },
  { id: 'outer', r0: 4400, r1: CITY.outer, wealth: 0.16, spacing: 17, h: [4.5, 8], cover: 0.92 },
];

/* ---------------------------------------------------------------------------
   THE STREET PLAN

   Inside the wall the city is planned: radial avenues out to the gates, ring
   streets between them, blocks in the gaps. A building is placed only if it
   is clear of a street and clear of a reserved precinct.
   ------------------------------------------------------------------------ */

const AVENUES = 16;                 // radial, six of them run to gates
const AVENUE_WIDTH = 20;
const RING_STREETS = [620, 1200, 1750, 2350, 3000, 3620, 4300, 4980];
const RING_WIDTH = 13;

/* Reserved precincts: the landmarks own their ground and no housing intrudes. */
function reservedZones() {
  const palaceR = Math.sqrt(CITY.palaceArea / Math.PI) * 1.18;   // ~300 m
  const marketR = Math.sqrt(CITY.marketArea / Math.PI);          // ~196 m
  return [
    { x: 0, z: 0, r: palaceR, id: 'palace' },
    { x: 520, z: -180, r: 190, id: 'temple' },
    { x: -430, z: 300, r: 150, id: 'granaries' },
    { x: -300, z: -520, r: 130, id: 'treasury' },
    { x: 250, z: 560, r: 120, id: 'prison' },
    { x: 1560, z: 260, r: marketR, id: 'market' },
    { x: -2100, z: -1500, r: 220, id: 'academy' },
    { x: 2600, z: -1900, r: 170, id: 'barracks' },
    { x: -1500, z: 2400, r: 150, id: 'healers' },
  ];
}

function onStreet(r, theta) {
  for (const rs of RING_STREETS) if (Math.abs(r - rs) < RING_WIDTH * 0.5) return true;
  const a = ((theta % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2);
  const step = (Math.PI * 2) / AVENUES;
  const nearest = Math.round(a / step) * step;
  /* Avenue width is a fixed distance on the ground, so it narrows in angle as
     it runs outward, which is what a real radial plan looks like. */
  const arc = Math.abs(a - nearest) * Math.max(r, 1);
  return arc < AVENUE_WIDTH * 0.5;
}

function inReserved(x, z, zones) {
  for (const zn of zones) {
    if ((x - zn.x) * (x - zn.x) + (z - zn.z) * (z - zn.z) < zn.r * zn.r) return zn;
  }
  return null;
}

/* ---------------------------------------------------------------------------
   THE GENERATOR
   ------------------------------------------------------------------------ */

/**
 * @param {object} opts
 * @param {number} opts.detail 1 for the full Street build, 0.22 for Regional
 *        blocks. Scales spacing, which is the honest way to drop density:
 *        fewer, larger buildings covering the same ground.
 */
export function generateCity(opts = {}) {
  const detail = opts.detail === undefined ? 1 : opts.detail;
  const rng = makeRng(seedFrom('sundisk-city'));
  const zones = reservedZones();

  const houses = [];   // {x,z,w,d,h,rot,gold,tone,wear}
  const silos = [];
  const towers = [];
  const tents = [];
  const stalls = [];

  const spacingScale = 1 / Math.max(0.12, detail);

  /* ---- inside the wall: the planned city ------------------------------- */
  for (const d of DISTRICTS) {
    const spacing = d.spacing * spacingScale;
    /* Walk the ring in concentric bands so the density is uniform per unit
       area rather than per unit angle. */
    for (let r = d.r0 + spacing * 0.5; r < d.r1; r += spacing) {
      const count = Math.max(4, Math.round((2 * Math.PI * r) / spacing));
      for (let i = 0; i < count; i++) {
        const theta = (i / count) * Math.PI * 2 + (rng() - 0.5) * 0.35 / Math.max(1, r / 200);
        const rr = r + (rng() - 0.5) * spacing * 0.42;
        if (rr < d.r0 || rr >= d.r1) continue;
        if (onStreet(rr, theta)) continue;
        if (rng() > d.cover) continue;

        const x = Math.cos(theta) * rr, z = Math.sin(theta) * rr;
        if (inReserved(x, z, zones)) continue;

        /* Footprints nearly fill their cell. A dense city has party walls and
           courtyards, not detached houses on plots, and the gap between two
           buildings is an alley, not a garden. */
        const w = spacing * (0.72 + rng() * 0.26);
        const dep = spacing * (0.70 + rng() * 0.28);
        const h = d.h[0] + rng() * (d.h[1] - d.h[0]);
        const importance = 0.3 + rng() * 0.5;
        houses.push({
          x, z, w, d: dep, h,
          /* Buildings face the street, which here means facing the centre. */
          rot: theta + Math.PI / 2 + (rng() - 0.5) * 0.14,
          gold: goldRatio(rr, d.wealth, importance),
          tone: rng(), wear: 0.18 + rng() * 0.3,
        });
      }
    }
  }

  /* ---- the Commons: no grid, no plan ------------------------------------
     Clustered on wells and shared ovens, thinning outward into open desert,
     with the trades canon puts downwind actually downwind. */
  const wells = [];
  {
    const nWells = Math.round(46 * Math.max(0.3, detail));
    for (let i = 0; i < nWells; i++) {
      const a = rng() * Math.PI * 2;
      const rr = CITY.wall + 120 + Math.pow(rng(), 0.75) * (CITY.commons - CITY.wall - 300);
      wells.push({ x: Math.cos(a) * rr, z: Math.sin(a) * rr, r: 220 + rng() * 260 });
    }
    /* Caravanserai at every gate approach, where the roads actually arrive. */
    for (const g of CITY.gates) {
      const a = (g.bearing - 90) * Math.PI / 180;
      for (let k = 0; k < (g.service ? 2 : 4); k++) {
        wells.push({
          x: Math.cos(a) * (CITY.wall + 260 + k * 300) + (rng() - 0.5) * 260,
          z: Math.sin(a) * (CITY.wall + 260 + k * 300) + (rng() - 0.5) * 260,
          r: 300, caravanserai: !g.service,
        });
      }
    }
  }

  const commonsCount = Math.round(11000 * Math.max(0.1, detail));
  const dw = CITY.downwind;
  for (let i = 0; i < commonsCount; i++) {
    /* Pick a cluster, then scatter around it. Clusters overlap and merge,
       which is exactly how unplanned settlement grows. */
    const wsel = wells[Math.floor(rng() * wells.length)];
    const a = rng() * Math.PI * 2;
    const rad = Math.pow(rng(), 0.62) * wsel.r;
    const x = wsel.x + Math.cos(a) * rad;
    const z = wsel.z + Math.sin(a) * rad;
    const rr = Math.hypot(x, z);
    if (rr < CITY.wall + 40 || rr > CITY.commons + 400) continue;

    /* Thinning into the desert at the fringe, where the tents are. */
    const fringe = Math.max(0, (rr - (CITY.commons - 1400)) / 1400);
    if (rng() < fringe * 0.85) {
      tents.push({ x, z, s: 3.0 + rng() * 2.6, rot: rng() * Math.PI, wear: 0.5 + rng() * 0.5 });
      continue;
    }

    /* Downwind side is where the slave quarters and the dirty trades are, so
       it is denser, lower and more worn. */
    const downwindness = (x * dw.x + z * dw.z) / Math.max(rr, 1);
    const poor = 0.5 + 0.5 * downwindness;
    const w = 4.2 + rng() * 5.2 - poor * 1.1;
    const dep = 4.0 + rng() * 5.0 - poor * 1.0;
    houses.push({
      x, z, w: Math.max(2.6, w), d: Math.max(2.6, dep),
      h: 2.5 + rng() * 2.0 - poor * 0.4,
      rot: rng() * Math.PI,
      gold: 0,                                  // no gold in anyone's walls out here
      tone: rng() * 0.7,
      wear: 0.45 + rng() * 0.55,
    });
  }

  /* Kilns, tanneries and dye pits at the far downwind edge. */
  {
    const n = Math.round(70 * Math.max(0.2, detail));
    for (let i = 0; i < n; i++) {
      const spread = 0.55;
      const base = Math.atan2(dw.z, dw.x) + (rng() - 0.5) * spread;
      const rr = CITY.commons - 900 + rng() * 1500;
      const x = Math.cos(base) * rr, z = Math.sin(base) * rr;
      silos.push({ x, z, r: 2.2 + rng() * 2.0, h: 3.0 + rng() * 3.5, kiln: true,
                   tone: rng() * 0.3, wear: 0.85 + rng() * 0.15 });
    }
  }

  return { houses, silos, towers, tents, stalls, wells, zones };
}

/* ---------------------------------------------------------------------------
   BUILD
   ------------------------------------------------------------------------ */

/* THE BUCKETS ARE WEDGE SEGMENTS, NOT WEDGES.

   Splitting the city into twelve angular sectors alone is not enough, and it
   is worth writing down why, because it cost a measurement to find. A wedge
   runs from the palace out to the edge of the Commons, nine kilometres. An
   InstancedMesh is culled whole or not at all, so any wedge the camera can
   see a corner of is drawn along its entire nine kilometre length. Standing
   in the Grand Market that means the whole city, every frame, and twice more
   for the shadow cascades.

   Cutting radially as well at the ring boundaries turns each bucket into a
   segment a couple of kilometres across, which the frustum can actually
   reject. The boundaries are the canon ones, so the cut lines fall on the
   walls and the ring roads rather than across them. */
const RING_EDGES = [1200, 3000, 5500, 9000, 1e9];

/**
 * Turn generated data into instanced meshes, split into wedge segments so
 * frustum culling can drop most of the city on any given frame. The wall
 * rings and the sector wedges are the natural portals Part 2 asks for.
 */
function buildInstances(data, material, sectors = 12) {
  const geo = geometryKit();
  const group = new THREE.Group();
  const rings = RING_EDGES.length;
  const bucketOf = (x, z) => {
    const a = Math.atan2(z, x);
    const s = Math.floor(((a + Math.PI) / (Math.PI * 2)) * sectors) % sectors;
    const r = Math.hypot(x, z);
    let ring = 0;
    while (ring < rings - 1 && r > RING_EDGES[ring]) ring++;
    return s * rings + ring;
  };
  const nameOf = (kind, b) => `sundisk-${kind}-${Math.floor(b / rings)}-${b % rings}`;

  const houseSets = [], siloSets = [], tentSets = [];
  for (let i = 0; i < sectors * rings; i++) {
    houseSets.push(new InstanceSet(geo.house, material, 512));
    siloSets.push(new InstanceSet(geo.silo, material, 32));
    tentSets.push(new InstanceSet(geo.cone, material, 64));
  }

  for (const h of data.houses) {
    houseSets[bucketOf(h.x, h.z)].add(h.x, G, h.z, h.w, h.h, h.d, h.rot, h.gold, h.tone, h.wear);
  }
  for (const s of data.silos) {
    siloSets[bucketOf(s.x, s.z)].add(s.x, G, s.z, s.r * 2, s.h, s.r * 2, 0, 0, s.tone, s.wear);
  }
  for (const t of data.tents) {
    tentSets[bucketOf(t.x, t.z)].add(t.x, G, t.z, t.s, t.s * 0.75, t.s, t.rot, 0, 0.85, t.wear);
  }

  let count = 0;
  for (let i = 0; i < sectors * rings; i++) {
    for (const [set, kind] of [[houseSets[i], 'houses'], [siloSets[i], 'kilns'], [tentSets[i], 'tents']]) {
      const m = set.build(nameOf(kind, i));
      if (m) { group.add(m); count += set.n; }
    }
  }
  group.userData.instanceCount = count;
  return group;
}

/* ---------------------------------------------------------------------------
   THE LANDMARKS
   ------------------------------------------------------------------------ */

/** The Royal Palace: 50 acres of interconnected buildings around courtyards. */
function buildPalace(material) {
  const geo = geometryKit();
  const set = new InstanceSet(geo.house, material, 128);
  const rng = makeRng(seedFrom('palace'));

  /* Six courtyards on a rough grid, wings between them. Not one block: canon
     is explicit that the palace is interconnected buildings around courts. */
  const courts = [
    [0, 0, 120, 120], [-180, -140, 90, 80], [180, -140, 90, 80],
    [-180, 150, 90, 80], [180, 150, 90, 80], [0, 250, 110, 70],
  ];
  for (const [cx, cz, cw, cd] of courts) {
    const wing = 26 + rng() * 8;
    const h = 11 + rng() * 6;
    const gold = goldRatio(Math.hypot(cx, cz), 1.0, 0.95);
    /* Four wings around the court. */
    set.add(cx, G, cz - cd / 2 - wing / 2, cw + wing * 2, h, wing, 0, gold, 0.8, 0.05);
    set.add(cx, G, cz + cd / 2 + wing / 2, cw + wing * 2, h, wing, 0, gold, 0.8, 0.05);
    set.add(cx - cw / 2 - wing / 2, G, cz, wing, h, cd, 0, gold, 0.8, 0.05);
    set.add(cx + cw / 2 + wing / 2, G, cz, wing, h, cd, 0, gold, 0.8, 0.05);
  }

  /* THE THRONE ROOM. Faces east to catch first light, with the dais at the
     origin, so at dawn the sun really does come in through the aperture and
     strike it. The east wall is left open as a colonnade rather than closed,
     which is what makes that true rather than decorative. */
  const throneW = 78, throneD = 54, throneH = 22;
  set.add(-throneW / 2 - 6, G, 0, 12, throneH, throneD + 24, 0, 1.0, 0.9, 0.02);  // west wall
  set.add(0, G, -throneD / 2 - 6, throneW, throneH, 12, 0, 1.0, 0.9, 0.02);       // north wall
  set.add(0, G, throneD / 2 + 6, throneW, throneH, 12, 0, 1.0, 0.9, 0.02);        // south wall
  /* Eastern colonnade: piers with the aperture between them. */
  for (let i = -3; i <= 3; i++) {
    if (i === 0) continue;                     // the aperture itself
    set.add(throneW / 2 + 4, G, i * 7.6, 6, throneH, 4.4, 0, 1.0, 0.95, 0.02);
  }
  /* The dais. Its top surface centre is the origin of the world. */
  set.add(0, G, 0, 14, -G, 14, 0, 1.0, 1.0, 0.0);

  /* The Sunset Wing, on the west face. */
  set.add(-340, G, 0, 60, 15, 150, 0, goldRatio(340, 1.0, 0.9), 0.85, 0.05);

  const mesh = set.build('palace');
  const grp = new THREE.Group();
  if (mesh) grp.add(mesh);
  grp.name = 'royal-palace';
  return grp;
}

/**
 * The Great Sun Temple, in the Djenne form language: mud-brick mass,
 * projecting toron beams in regular rows, tapering buttress pilasters,
 * rounded parapets, and three towers for dawn, noon and dusk, each capped
 * with an ostrich-egg pinnacle.
 */
function buildTemple(material) {
  const geo = geometryKit();
  const body = new InstanceSet(geo.house, material, 512);
  const eggs = new InstanceSet(geo.egg, material, 8);
  const rng = makeRng(seedFrom('sun-temple'));

  const cx = 520, cz = -180;
  const W = 132, D = 96, H = 17;          // capacity 10,000 at the canon figure
  const gold = goldRatio(Math.hypot(cx, cz), 1.0, 1.0);

  body.add(cx, G, cz, W, H, D, 0, gold * 0.8, 0.72, 0.12);

  /* Tapering buttress pilasters down every face, the Djenne signature. */
  const pil = 3.4;
  for (let i = -6; i <= 6; i++) {
    const px = cx + i * (W / 13);
    body.add(px, G, cz - D / 2 - pil / 2, pil, H * 1.14, pil, 0, gold * 0.85, 0.7, 0.1);
    body.add(px, G, cz + D / 2 + pil / 2, pil, H * 1.14, pil, 0, gold * 0.85, 0.7, 0.1);
  }
  for (let j = -4; j <= 4; j++) {
    const pz = cz + j * (D / 9);
    body.add(cx - W / 2 - pil / 2, G, pz, pil, H * 1.14, pil, 0, gold * 0.85, 0.7, 0.1);
    body.add(cx + W / 2 + pil / 2, G, pz, pil, H * 1.14, pil, 0, gold * 0.85, 0.7, 0.1);
  }

  /* Toron: palm beams projecting from the walls in regular rows. They are the
     permanent scaffolding the annual replastering is done from, so they are
     structural, not ornament. */
  for (let row = 0; row < 3; row++) {
    const y = G + 5 + row * 4.4;
    for (let i = -8; i <= 8; i++) {
      const px = cx + i * (W / 17);
      body.add(px, y, cz - D / 2 - 0.9, 0.32, 0.32, 2.6, 0, 0, 0.25, 0.4);
      body.add(px, y, cz + D / 2 + 0.9, 0.32, 0.32, 2.6, 0, 0, 0.25, 0.4);
    }
    for (let j = -5; j <= 5; j++) {
      const pz = cz + j * (D / 11);
      body.add(cx - W / 2 - 0.9, y, pz, 2.6, 0.32, 0.32, 0, 0, 0.25, 0.4);
      body.add(cx + W / 2 + 0.9, y, pz, 2.6, 0.32, 0.32, 0, 0, 0.25, 0.4);
    }
  }

  /* Three towers: dawn, noon and dusk. Dawn faces east. */
  const towers = [
    { dx: W / 2 - 12, dz: 0, h: 34, name: 'dawn' },
    { dx: 0, dz: -D / 2 + 10, h: 40, name: 'noon' },
    { dx: -W / 2 + 12, dz: 0, h: 34, name: 'dusk' },
  ];
  for (const t of towers) {
    body.add(cx + t.dx, G, cz + t.dz, 15, t.h, 15, 0, gold, 0.78, 0.08);
    eggs.add(cx + t.dx, G + t.h, cz + t.dz, 5.4, 5.4, 5.4, 0, 1.0, 1.0, 0.0);
  }

  const grp = new THREE.Group();
  const b = body.build('temple');
  const e = eggs.build('temple-pinnacles');
  if (b) grp.add(b);
  if (e) grp.add(e);
  grp.name = 'great-sun-temple';
  return grp;
}

/** Seven great families, seven minor palaces, each competing. */
function buildNobleQuarter(material) {
  const geo = geometryKit();
  const set = new InstanceSet(geo.house, material, 256);
  const rng = makeRng(seedFrom('noble-quarter'));
  for (let f = 0; f < 7; f++) {
    const a = (f / 7) * Math.PI * 2 + 0.4;
    const rr = 820 + rng() * 180;
    const cx = Math.cos(a) * rr, cz = Math.sin(a) * rr;
    /* Each family gets a distinct massing and a distinct gold ratio, because
       the competition between them is the point. */
    const style = f % 3;
    const wealth = 0.78 + (f % 5) * 0.045;
    const gold = goldRatio(rr, wealth, 0.9);
    const n = 4 + style;
    for (let i = 0; i < n; i++) {
      const ia = (i / n) * Math.PI * 2;
      const ir = 34 + style * 10;
      set.add(cx + Math.cos(ia) * ir, G, cz + Math.sin(ia) * ir,
        22 + rng() * 12, 10 + style * 4 + rng() * 5, 18 + rng() * 10,
        ia, gold, 0.7 + rng() * 0.3, 0.04 + rng() * 0.08);
    }
    /* The walled garden, which is what the water is actually for. */
    for (let s = 0; s < 4; s++) {
      const sa = s * Math.PI / 2;
      set.add(cx + Math.cos(sa) * 72, G, cz + Math.sin(sa) * 72,
        s % 2 ? 3 : 144, 4.2, s % 2 ? 144 : 3, 0, gold * 0.5, 0.6, 0.1);
    }
  }
  const grp = new THREE.Group();
  const m = set.build('noble-quarter');
  if (m) grp.add(m);
  return grp;
}

/** The Royal Granaries: massive round mud-brick silos, guarded. */
function buildGranaries(material) {
  const geo = geometryKit();
  const set = new InstanceSet(geo.silo, material, 32);
  const rng = makeRng(seedFrom('granaries'));
  const cx = -430, cz = 300;
  for (let i = 0; i < 14; i++) {
    const a = (i / 14) * Math.PI * 2;
    const rr = 45 + (i % 3) * 30;
    set.add(cx + Math.cos(a) * rr, G, cz + Math.sin(a) * rr,
      17 + rng() * 5, 19 + rng() * 6, 17 + rng() * 5, 0,
      goldRatio(Math.hypot(cx, cz), 0.7, 0.6), 0.55 + rng() * 0.2, 0.15);
  }
  const grp = new THREE.Group();
  const m = set.build('royal-granaries');
  if (m) grp.add(m);
  return grp;
}

/**
 * The Grand Market: 30 acres sectioned by trade. Gold, salt, textile, spice,
 * livestock, and the slave traders behind their euphemism.
 */
function buildMarket(material) {
  const geo = geometryKit();
  const stalls = new InstanceSet(geo.box, material, 3000);
  const awnings = new InstanceSet(geo.plane, material, 3000);
  const rng = makeRng(seedFrom('grand-market'));
  const cx = 1560, cz = 260;
  const R = Math.sqrt(CITY.marketArea / Math.PI);

  const trades = [
    { name: 'gold', gold: 0.55, tone: 0.9 },
    { name: 'salt', gold: 0.20, tone: 0.95 },
    { name: 'textile', gold: 0.12, tone: 0.5 },
    { name: 'spice', gold: 0.10, tone: 0.35 },
    { name: 'livestock', gold: 0.04, tone: 0.6 },
    { name: 'the block', gold: 0.06, tone: 0.2 },
  ];

  for (let t = 0; t < trades.length; t++) {
    const a0 = (t / trades.length) * Math.PI * 2;
    const a1 = ((t + 1) / trades.length) * Math.PI * 2;
    const tr = trades[t];
    for (let i = 0; i < 340; i++) {
      const a = a0 + rng() * (a1 - a0) * 0.94;
      const rr = 18 + Math.sqrt(rng()) * (R - 24);
      const x = cx + Math.cos(a) * rr, z = cz + Math.sin(a) * rr;
      const w = 2.6 + rng() * 1.6, d = 2.2 + rng() * 1.4;
      stalls.add(x, G, z, w, 2.3 + rng() * 0.6, d, a, tr.gold * 0.3, tr.tone, 0.3 + rng() * 0.3);
      awnings.add(x, G + 2.9, z, w * 1.7, 1, d * 1.7, a + (rng() - 0.5) * 0.3,
        0, tr.tone, 0.2 + rng() * 0.4);
    }
  }

  const grp = new THREE.Group();
  const s = stalls.build('market-stalls');
  const aw = awnings.build('market-awnings');
  if (s) grp.add(s);
  if (aw) grp.add(aw);
  grp.name = 'grand-market';
  return grp;
}

/** Tomorrow's Lions Academy: training yards, barracks, a scarred sand ground. */
function buildAcademy(material) {
  const geo = geometryKit();
  const set = new InstanceSet(geo.house, material, 64);
  const rng = makeRng(seedFrom('tomorrows-lions'));
  const cx = -2100, cz = -1500;
  /* Barracks in ranks, because that is how an academy with a 35 percent
     survival rate houses its intake. */
  for (let i = 0; i < 12; i++) {
    const row = Math.floor(i / 4), col = i % 4;
    set.add(cx - 90 + col * 52, G, cz - 60 + row * 46, 40, 6.5, 16, 0,
      goldRatio(Math.hypot(cx, cz), 0.2, 0.4), 0.4 + rng() * 0.2, 0.35);
  }
  /* The wall around the scarred ground. */
  for (let s = 0; s < 4; s++) {
    const a = s * Math.PI / 2;
    set.add(cx + Math.cos(a) * 130, G, cz + Math.sin(a) * 130,
      s % 2 ? 4 : 260, 5, s % 2 ? 260 : 4, 0, 0.02, 0.35, 0.5);
  }
  const grp = new THREE.Group();
  const m = set.build('academy');
  if (m) grp.add(m);
  return grp;
}

/* ---------------------------------------------------------------------------
   PUBLIC BUILDERS
   ------------------------------------------------------------------------ */

export function buildSundiskFull(ctx) {
  const grp = new THREE.Group();
  grp.name = 'sundisk-full';
  const mat = ctx.sunklay;

  const data = generateCity({ detail: 1 });
  const city = buildInstances(data, mat, 12);
  grp.add(city);

  grp.add(buildPalace(mat));
  grp.add(buildTemple(mat));
  grp.add(buildNobleQuarter(mat));
  grp.add(buildGranaries(mat));
  grp.add(buildMarket(mat));
  grp.add(buildAcademy(mat));

  if (ctx.buildWall) grp.add(ctx.buildWall(ctx));
  if (ctx.buildVeil) grp.add(ctx.buildVeil(ctx));
  if (ctx.buildWater) grp.add(ctx.buildWater(ctx));
  if (ctx.buildCrowd) grp.add(ctx.buildCrowd(CITY));

  grp.userData.instanceCount = city.userData.instanceCount;
  /* The generator's own building list, handed to the character controller so
     collision is a 2D box test against a grid rather than a raycast against
     thirty-four thousand instances. */
  grp.userData.collisionRects = data.houses.map(h => ({
    x: h.x, z: h.z, w: h.w, d: h.d, h: h.h, rot: h.rot, baseY: G,
  }));
  return grp;
}

export function buildSundiskBlocks(ctx) {
  const grp = new THREE.Group();
  grp.name = 'sundisk-blocks';
  const mat = ctx.sunklay;

  const data = generateCity({ detail: 0.42 });
  grp.add(buildInstances(data, mat, 8));
  grp.add(buildPalace(mat));
  grp.add(buildTemple(mat));
  grp.add(buildGranaries(mat));
  if (ctx.buildWall) grp.add(ctx.buildWall(ctx));
  if (ctx.buildVeil) grp.add(ctx.buildVeil(ctx));
  return grp;
}

/**
 * Beyond eight kilometres the city is a footprint, not buildings: the glowing
 * extent Part 1.4 asks for at Kingdom tier, with the wall ring reading as a
 * hard edge and the Commons as a spreading stain outside it.
 */
export function buildSundiskImposter(ctx) {
  const grp = new THREE.Group();
  grp.name = 'sundisk-imposter';

  const disc = (r0, r1, color, opacity, y) => {
    const g = new THREE.RingGeometry(r0, r1, 96, 1);
    g.rotateX(-Math.PI / 2);
    const m = new THREE.MeshBasicMaterial({
      color, transparent: true, opacity, depthWrite: false, side: THREE.DoubleSide,
    });
    m.userData.ownedByRegion = true;
    const mesh = new THREE.Mesh(g, m);
    mesh.position.y = CITY_GROUND_Y + y;
    mesh.renderOrder = 2;
    return mesh;
  };

  grp.add(disc(0, CITY.inner, 0xd9a83a, 0.85, 3.0));
  grp.add(disc(CITY.inner, CITY.middle, 0xa07f42, 0.72, 2.6));
  grp.add(disc(CITY.middle, CITY.outer, 0x7d6647, 0.66, 2.2));
  grp.add(disc(CITY.outer, CITY.outer + 26, 0xe8c46a, 0.9, 3.4));      // the wall itself
  grp.add(disc(CITY.outer + 26, CITY.commons, 0x5d5040, 0.44, 1.8));   // the Commons

  return grp;
}
